name: denoiserexample
channels:
  - defaults
dependencies:
  - python=3.7
  - flask=1.1.2
  - matplotlib=3.3.1
  - pillow=7.2.0
  - pip 
  - pip:
    - opencv-python==4.4.0.42
    - tensorflow==2.2.0
    - keras==2.4.3

